- name: Update apt cache
  apt: update_cache=yes
  tags:
    - app
    - php

- name: PHP | Install Ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php' update_cache=yes
  tags:
    - app
    - php

- name: PHP | Install PHP 7.4
  apt: pkg=php7.4 state=latest
  tags:
    - app
    - php

- name: PHP | Install PHP Modules
  apt:
    pkg:
      - php-fpm
      - php7.4-mysql
      - php-pear
      - php7.4-curl
      - php7.4-bcmath
      - php7.4-mbstring
      - php7.4-intl
    state: present
  tags:
    - app
    - php

- name: Tune php.ini
  template: src=php7/fpm/php.ini.j2 dest=/etc/php/7.4/fpm/php.ini backup=yes
  notify:
    - reload php7-fpm
  tags:
    - app
    - php
    - php-config

- name: Tune php php7/fpm/pool.d/www.conf
  template: src=php7/fpm/pool.d/www.conf.j2 dest=/etc/php/7.4/fpm/pool.d/www.conf backup=yes
  notify:
    - reload php7-fpm
  tags:
    - app
    - php
    - php-config

- name: Install xdebug
  apt:
    pkg:
      - php7.4-xdebug
    state: present
  when: app_role != 'production'
  tags:
    - php

- name: Tune php mods-available/xdebug.ini
  template: src=php7/mods-available/xdebug.ini.j2 dest=/etc/php/7.3/mods-available/xdebug.ini backup=yes
  when: app_role != 'production'
  notify:
    - reload php7-fpm
  tags:
    - app
    - php
    - php-config
